import { chromium } from '@playwright/test';
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
p.on('dialog', d => d.accept());
await p.goto('http://localhost:3000/projects/PRJ-ASL'); await p.waitForLoadState('networkidle');
await p.getByRole('heading', { name: '3 · Tinjau dan koreksi' }).scrollIntoViewIfNeeded();
await p.screenshot({ path: '/private/tmp/claude-501/-Users-macbookpro-Projects-clara/aeabea17-34af-425f-9558-534c86df2fbe/scratchpad/review.png' });
await p.getByRole('button', { name: /Setujui sebagai acuan V1/ }).click();
await p.getByRole('tab', { name: /Ringkasan/ }).waitFor();
const post = (path, body) => p.evaluate(([path, body]) => fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }), [path, body]);
await post('/api/projects/PRJ-ASL/events', { type: 'PROGRESS_UPDATED', progress: 60 });
await post('/api/projects/PRJ-ASL/costs', { amount: 64000000, description: 'Biaya tim', category: 'DEVELOPMENT' });
await post('/api/projects/PRJ-ASL/events', { type: 'MILESTONE_COMPLETED', milestoneId: 'MLS-1' });
await post('/api/projects/PRJ-ASL/events', { type: 'REVISION_LOGGED', revisionCount: 5 });
await p.goto('http://localhost:3000/projects/PRJ-ASL?tab=alerts'); await p.waitForLoadState('networkidle');
await p.locator('article', { hasText: 'belum ditagih' }).getByRole('button', { name: 'Lihat bukti' }).click();
await p.waitForTimeout(400); await p.screenshot({ path: '/private/tmp/claude-501/-Users-macbookpro-Projects-clara/aeabea17-34af-425f-9558-534c86df2fbe/scratchpad/drawer.png' });
await b.close();
