import { Project, Alert } from '@/types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'PRJ-001',
    name: 'Sistem ERP Core & Supply Chain Modernization',
    client: 'PT Astra Sahabat Logistik',
    status: 'AT_RISK',
    contractValue: 1850000000,
    plannedCost: 1200000000,
    actualCost: 1340000000,
    billableValue: 1110000000,
    billedValue: 555000000,
    paidValue: 555000000,
    progress: 65,
    baselineVersion: 'V1.0',
    startDate: '2026-06-01',
    endDate: '2026-12-15',
    activeRevisionCount: 4,
    agreementBaseline: {
      contractNumber: 'ASL/IT/PKS/2026/089',
      title: 'Perjanjian Kerja Sama Pengembangan Core ERP Logistics',
      clientName: 'PT Astra Sahabat Logistik',
      contractValue: 1850000000,
      startDate: '2026-06-01',
      deadline: '2026-12-15',
      paymentTerms: 'Termin bertahap 30% DP, 30% UAT Modul 1-3, 30% Go-Live, 10% Retensi 90 hari.',
      revisionLimit: 3,
      scopeItems: [
        {
          id: 'SCP-101',
          title: 'Warehouse Inventory & Stock Multi-Depot',
          description: 'Modul pelacakan stok real-time di 14 depo distribusi.',
          category: 'CORE_FEATURE',
          status: 'MATCH',
          contractClauseRef: 'Pasal 4 Ayat 2 (Lampiran Teknis A)',
        },
        {
          id: 'SCP-102',
          title: 'Fleet & Dispatch Routing Optimization',
          description: 'Algoritma rute armada pengiriman logistik Jabodetabek.',
          category: 'CORE_FEATURE',
          status: 'MATCH',
          contractClauseRef: 'Pasal 4 Ayat 3',
        },
        {
          id: 'SCP-103',
          title: 'Integrasi SAP Gateway Non-Standard',
          description: 'Pengerjaan connector REST-to-RFC SAP custom atas permintaan tim vendor depo tanpa adendum.',
          category: 'INTEGRATION',
          status: 'NEEDS_REVIEW',
          deviationNotes: 'Tidak tercantum pada SOW awal. Menghabiskan 120 jam man-hours tambahan developer.',
        },
        {
          id: 'SCP-104',
          title: 'Modul Finance & Invoice Reconciliation',
          description: 'Sinkronisasi billing dengan software akuntansi internal.',
          category: 'CORE_FEATURE',
          status: 'MATCH',
          contractClauseRef: 'Pasal 5 Ayat 1',
        },
      ],
      milestones: [
        {
          id: 'MLS-01',
          title: 'Termin 1: Down Payment & SRS Sign-off (30%)',
          percentage: 30,
          value: 555000000,
          targetDate: '2026-06-20',
          completionDate: '2026-06-18',
          status: 'COMPLETED',
          billingStatus: 'PAID',
          invoiceId: 'INV-2026-001',
        },
        {
          id: 'MLS-02',
          title: 'Termin 2: UAT Modul Core & Deployment Staging (30%)',
          percentage: 30,
          value: 555000000,
          targetDate: '2026-09-15',
          completionDate: '2026-09-20',
          status: 'COMPLETED',
          billingStatus: 'UNBILLED',
          evidenceSnippet: 'UAT Sign-off telah ditandatangani PM Astra per 20 Sept 2026, namun invoice belum diterbitkan oleh finance.',
        },
        {
          id: 'MLS-03',
          title: 'Termin 3: Production Rollout & Go-Live (30%)',
          percentage: 30,
          value: 555000000,
          targetDate: '2026-11-20',
          status: 'IN_PROGRESS',
          billingStatus: 'UNBILLED',
        },
        {
          id: 'MLS-04',
          title: 'Termin 4: Final Acceptance & Retensi (10%)',
          percentage: 10,
          value: 185000000,
          targetDate: '2026-12-15',
          status: 'PENDING',
          billingStatus: 'UNBILLED',
        },
      ],
      clausesSummary: [
        {
          clauseNumber: 'Pasal 6 Ayat 3',
          title: 'Batas Revisi & Permintaan Tambahan',
          description: 'Klien berhak mengajukan maksimal 3 (tiga) putaran revisi desain dan alur kerja. Revisi tambahan wajib melalui Change Request berbayar.',
        },
        {
          clauseNumber: 'Pasal 9 Ayat 2',
          title: 'Denda Keterlambatan Termin Pembayaran',
          description: 'Pembayaran invoice wajib diselesaikan klien maksimal 14 hari kalender kerja setelah Berita Acara diterima.',
        },
      ],
    },
    planBaseline: {
      totalPlannedCost: 1200000000,
      contingencyBudget: 60000000,
      items: [
        { id: 'RAB-1', category: 'Engineering Team', description: 'Tech Lead, 3 Fullstack Dev, 1 QA (6 Bulan)', plannedAmount: 780000000, actualAmount: 890000000 },
        { id: 'RAB-2', category: 'Cloud Infrastructure', description: 'AWS Staging & Production Cluster, RDS', plannedAmount: 180000000, actualAmount: 210000000 },
        { id: 'RAB-3', category: 'Third-party Licenses', description: 'Maps API & SMS OTP Enterprise Gateway', plannedAmount: 120000000, actualAmount: 120000000 },
        { id: 'RAB-4', category: 'Project Management & Ops', description: 'PM, Scrum Master & Onsite Workshop', plannedAmount: 120000000, actualAmount: 120000000 },
      ],
    },
    actualCosts: [
      { id: 'CST-01', projectId: 'PRJ-001', date: '2026-06-30', category: 'DEVELOPMENT', description: 'Sprint 1-2 Engineer Payroll', amount: 130000000, submittedBy: 'Finance Ops' },
      { id: 'CST-02', projectId: 'PRJ-001', date: '2026-07-31', category: 'DEVELOPMENT', description: 'Sprint 3-4 Engineer Payroll', amount: 130000000, submittedBy: 'Finance Ops' },
      { id: 'CST-03', projectId: 'PRJ-001', date: '2026-08-31', category: 'DEVELOPMENT', description: 'Sprint 5-6 Engineer Payroll + Overtime', amount: 165000000, submittedBy: 'Finance Ops' },
      { id: 'CST-04', projectId: 'PRJ-001', date: '2026-09-15', category: 'INFRASTRUCTURE', description: 'AWS Cloud Overage & Multi-AZ RDS', amount: 85000000, submittedBy: 'DevOps Lead' },
      { id: 'CST-05', projectId: 'PRJ-001', date: '2026-09-30', category: 'DEVELOPMENT', description: 'Sprint 7-8 Engineer Payroll + Custom SAP Work', amount: 175000000, submittedBy: 'Finance Ops' },
    ],
    invoices: [
      {
        id: 'INV-2026-001',
        invoiceNumber: 'INV/2026/06/0045',
        projectId: 'PRJ-001',
        milestoneId: 'MLS-01',
        milestoneTitle: 'Termin 1: Down Payment (30%)',
        amount: 555000000,
        status: 'PAID',
        issueDate: '2026-06-19',
        dueDate: '2026-07-03',
        paymentDate: '2026-07-01',
      },
    ],
    events: [
      { id: 'EVT-01', projectId: 'PRJ-001', type: 'MILESTONE_COMPLETED', title: 'Kickoff & DP Diterima', description: 'Termin 1 senilai Rp 555.000.000 lunas.', date: '2026-06-19', author: 'System' },
      { id: 'EVT-02', projectId: 'PRJ-001', type: 'SCOPE_ADDED', title: 'Permintaan Custom SAP Integration', description: 'Depo logistik meminta bridge RFC langsung tanpa approval adendum.', date: '2026-08-10', author: 'PM Budi' },
      { id: 'EVT-03', projectId: 'PRJ-001', type: 'REVISION_LOGGED', title: 'Revisi #4 UI Dashboard Depo', description: 'Klien meminta penyesuaian tata letak grid dan filter armada (Batas klausul kontrak adalah 3x).', date: '2026-09-12', author: 'UI/UX Designer' },
      { id: 'EVT-04', projectId: 'PRJ-001', type: 'MILESTONE_COMPLETED', title: 'UAT Modul 1-3 Selesai (Sign-off)', description: 'BAST Termin 2 sudah ditandatangani klien.', date: '2026-09-20', author: 'PM Budi' },
    ],
    changeRequests: [
      {
        id: 'CR-001',
        projectId: 'PRJ-001',
        crNumber: 'CR/ASL/2026/001',
        title: 'Adendum Penambahan SAP RFC Bridge Module',
        description: 'Melegalkan pekerjaan integrasi SAP non-standard menjadi add-on berbayar.',
        reason: 'Pekerjaan di luar SOW awal menimbulkan cost overrun teknis Rp 110.000.000.',
        additionalScope: ['SAP RFC Gateway Microservice', 'Data Sanitation Proxy'],
        additionalValue: 125000000,
        deadlineExtensionDays: 14,
        status: 'PENDING',
        createdAt: '2026-09-25',
      },
    ],
    alerts: [
      {
        id: 'ALT-101',
        projectId: 'PRJ-001',
        projectName: 'Sistem ERP Core & Supply Chain Modernization',
        type: 'BILLING_VARIANCE',
        severity: 'CRITICAL',
        title: 'Milestone UAT Selesai Tapi Belum Ditagihkan',
        description: 'Termin 2 (Rp 555.000.000) sudah diverifikasi selesai sejak 20 Sept 2026 namun invoice belum diajukan ke klien. Uang berpotensi macet.',
        rupiahImpact: 555000000,
        status: 'NEW',
        createdAt: '2026-09-22',
        evidence: {
          type: 'FINANCIAL_MISMATCH',
          title: 'UAT Completed vs Unbilled Termin',
          snippet: 'Agreement Baseline: Termin 2 jatuh tempo saat UAT Sign-off. Status aktual: BAST UAT signed 2026-09-20. Status Billing: UNBILLED.',
          sourceDocument: 'PKS ASL/IT/PKS/2026/089 Pasal 7 & BAST-02.pdf',
          pageOrSection: 'Pasal 7 Ayat 2',
          confidenceScore: 0.98,
        },
      },
      {
        id: 'ALT-102',
        projectId: 'PRJ-001',
        projectName: 'Sistem ERP Core & Supply Chain Modernization',
        type: 'BUDGET_VARIANCE',
        severity: 'HIGH',
        title: 'Actual Cost Melebihi Anggaran RAB (+11.6%)',
        description: 'Total pengeluaran riil mencapai Rp 1.340.000.000 melampaui RAB baseline Rp 1.200.000.000 sebesar Rp 140.000.000.',
        rupiahImpact: 140000000,
        status: 'NEW',
        createdAt: '2026-09-30',
        evidence: {
          type: 'FINANCIAL_MISMATCH',
          title: 'RAB Overrun Analysis',
          snippet: 'RAB Total: Rp 1.200.000.000. Actual Cost per 30 Sept: Rp 1.340.000.000. Selisih: -Rp 140.000.000 (Overbudget). Pemicu utama: engineering overtime & infrastructure burst.',
          sourceDocument: 'RAB_Final_Baseline_V1.xlsx vs Ledger_Sept2026',
          pageOrSection: 'Sheet: Cost Breakdown Baris 14',
          confidenceScore: 0.95,
        },
      },
      {
        id: 'ALT-103',
        projectId: 'PRJ-001',
        projectName: 'Sistem ERP Core & Supply Chain Modernization',
        type: 'SCOPE_VARIANCE',
        severity: 'HIGH',
        title: 'Pekerjaan di Luar Scope Kontrak Ditemukan',
        description: 'Fitur "Integrasi SAP Gateway Non-Standard" aktif dikerjakan developer tanpa adanya klausul pendukung di PKS awal.',
        rupiahImpact: 75000000,
        status: 'NEW',
        createdAt: '2026-09-15',
        evidence: {
          type: 'CONTRACT_CLAUSE',
          title: 'Scope Non-Compliance',
          snippet: 'PKS Pasal 4 hanya mencakup: Warehouse Stock, Fleet Routing, dan Finance Reconciliation. Pekerjaan SAP RFC Bridge tidak terdaftar dalam SOW sah.',
          sourceDocument: 'PKS ASL/IT/PKS/2026/089 Lampiran Teknis A',
          pageOrSection: 'Lampiran A Hal 12',
          confidenceScore: 0.92,
        },
      },
      {
        id: 'ALT-104',
        projectId: 'PRJ-001',
        projectName: 'Sistem ERP Core & Supply Chain Modernization',
        type: 'REVISION_LIMIT',
        severity: 'MEDIUM',
        title: 'Batas Revisi Kontrak Terlampaui (4 / 3)',
        description: 'Klien telah mengajukan 4 putaran revisi. Kontrak membatasi maksimal 3 revisi gratis sebelum dikenakan rate per man-day.',
        rupiahImpact: 35000000,
        status: 'NEW',
        createdAt: '2026-09-12',
        evidence: {
          type: 'EVENT_LOG',
          title: 'Klausul Batas Revisi vs Event Log',
          snippet: 'Pasal 6 Ayat 3: "Maksimal 3 (tiga) putaran revisi". Audit log menunjukkan event revisi ke-4 dicatat pada 12 Sept 2026.',
          sourceDocument: 'PKS ASL/IT/PKS/2026/089 Pasal 6',
          pageOrSection: 'Pasal 6 Ayat 3',
          confidenceScore: 0.99,
        },
      },
    ],
  },
  {
    id: 'PRJ-002',
    name: 'Mobile Banking Re-Platforming & Security Upgrade',
    client: 'PT Bank Mandiri Syariah',
    status: 'ACTIVE',
    contractValue: 2400000000,
    plannedCost: 1600000000,
    actualCost: 1150000000,
    billableValue: 1440000000,
    billedValue: 1440000000,
    paidValue: 960000000,
    progress: 60,
    baselineVersion: 'V2.0',
    startDate: '2026-05-10',
    endDate: '2027-01-31',
    activeRevisionCount: 2,
    agreementBaseline: {
      contractNumber: 'BMS/IT-DEV/2026/112',
      title: 'PKS Pembaruan Mobile Banking & Hardening Modul Transaksi',
      clientName: 'PT Bank Mandiri Syariah',
      contractValue: 2400000000,
      startDate: '2026-05-10',
      deadline: '2027-01-31',
      paymentTerms: 'Termin: 20% DP, 40% Sprint 1-4, 20% Security Audit, 20% Launch.',
      revisionLimit: 3,
      scopeItems: [
        { id: 'SCP-201', title: 'Biometric Login & FIDO2 Support', description: 'Autentikasi sidik jari & face id.', category: 'CORE_FEATURE', status: 'MATCH' },
        { id: 'SCP-202', title: 'QRIS & Transfer Real-time Engine', description: 'Modul transaksi switching.', category: 'CORE_FEATURE', status: 'MATCH' },
        { id: 'SCP-203', title: 'BI-FAST Direct Proxy Module', description: 'Disetujui melalui Change Request V2.0.', category: 'INTEGRATION', status: 'APPROVED_CHANGE' },
      ],
      milestones: [
        { id: 'MLS-21', title: 'Termin 1: Advance DP (20%)', percentage: 20, value: 480000000, targetDate: '2026-05-25', status: 'COMPLETED', billingStatus: 'PAID' },
        { id: 'MLS-22', title: 'Termin 2: Core Architecture & Sprint Review (40%)', percentage: 40, value: 960000000, targetDate: '2026-08-30', status: 'COMPLETED', billingStatus: 'PAID' },
        { id: 'MLS-23', title: 'Termin 3: Penetration Testing & ISO Audit (20%)', percentage: 20, value: 480000000, targetDate: '2026-11-15', status: 'IN_PROGRESS', billingStatus: 'UNBILLED' },
      ],
      clausesSummary: [],
    },
    planBaseline: {
      totalPlannedCost: 1600000000,
      contingencyBudget: 80000000,
      items: [],
    },
    actualCosts: [],
    invoices: [],
    events: [],
    changeRequests: [],
    alerts: [],
  },
  {
    id: 'PRJ-003',
    name: 'Smart Warehouse IoT & Telemetry Platform',
    client: 'PT Pelabuhan Solusi Prima',
    status: 'BASELINE_PENDING',
    contractValue: 950000000,
    plannedCost: 620000000,
    actualCost: 0,
    billableValue: 0,
    billedValue: 0,
    paidValue: 0,
    progress: 0,
    baselineVersion: 'DRAFT',
    startDate: '2026-10-15',
    endDate: '2027-03-31',
    activeRevisionCount: 0,
    agreementBaseline: {
      contractNumber: 'PSP/IOT/X/2026/003',
      title: 'PKS Implementasi Gateway Sensor IoT Dermaga & Pergudangan',
      clientName: 'PT Pelabuhan Solusi Prima',
      contractValue: 950000000,
      startDate: '2026-10-15',
      deadline: '2027-03-31',
      paymentTerms: '30% DP, 40% Delivery Hardware & Config, 30% Acceptance.',
      revisionLimit: 2,
      scopeItems: [
        { id: 'SCP-301', title: 'Sensor Suhu & Kelembaban IoT Gateway', description: 'Instalasi 40 node telemetry.', category: 'INFRASTRUCTURE', status: 'MATCH' },
        { id: 'SCP-302', title: 'Dashboard Realtime & Alerting SMS/WA', description: 'Monitoring status kontainer berpendingin.', category: 'CORE_FEATURE', status: 'MATCH' },
      ],
      milestones: [
        { id: 'MLS-31', title: 'Termin 1: Down Payment 30%', percentage: 30, value: 285000000, targetDate: '2026-10-25', status: 'PENDING', billingStatus: 'UNBILLED' },
      ],
      clausesSummary: [],
    },
    planBaseline: {
      totalPlannedCost: 620000000,
      contingencyBudget: 35000000,
      items: [],
    },
    actualCosts: [],
    invoices: [],
    events: [],
    changeRequests: [],
    alerts: [],
  },
];
